#cloud-config
coreos:
  units:
  - name: update-engine.service
    command: stop
  - name: locksmithd.service
    command: stop
  - name: mnt-shared.mount
    command: start
    content: |
      [Mount]
      What=${efs_id}.efs.${aws_region}.amazonaws.com:/
      Where=/mnt/shared
      Type=nfs
  - name: drone-server-secrets.service
    enable: true
    content: |
      [Unit]
      Description=DroneCI Server Secrets Writer
      After=docker.service
      Requires=docker.service
      [Install]
      WantedBy=multi-user.target
      [Service]
      TimeoutStartSec=0
      ExecStart=/usr/bin/docker run \
        --env "KMS_SECRETS_OUT_PATH=/secrets/secrets.env" \
        --env "AWS_DEFAULT_REGION=${aws_region}" \
        --env "KMS_DRONE_GITHUB_CLIENT=${kms_drone_github_client}" \
        --env "KMS_DRONE_GITHUB_SECRET=${kms_drone_github_secret}" \
        --env "KMS_DRONE_SECRET=${kms_drone_secret}" \
        --volume drone-server-secrets:/secrets \
        lrvick/kms-decrypt
  - name: drone-server.service
    enable: true
    content: |
      [Unit]
      Description=Drone CI Server
      Requires=drone-server-secrets.service
      After=drone-server-secrets.service
      [Install]
      WantedBy=multi-user.target
      [Service]
      Restart=always
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker kill %p
      ExecStartPre=-/usr/bin/docker rm %p
      ExecStartPre=/usr/bin/docker pull drone/drone:0.5
      ExecStart=/usr/bin/docker run \
        --name %p \
        --volume /mnt/shared/drone:/var/lib/drone \
        --volumes-from drone-server-secrets \
        --entrypoint "/bin/sh -c"
        --port 80:8000 \
        --env DRONE_OPEN=true \
        --env GITHUB=true \
        --env DRONE_ORGS="${drone_orgs}" \
        drone/drone "source /secrets/secrets.env; /usr/local/bin/droned"
      ExecStop=/usr/bin/docker stop %p
  - name: drone-agent-secrets.service
    enable: true
    content: |
      [Unit]
      Description=DroneCI Agent Secrets Writer
      Requires=docker.service
      After=docker.service
      [Install]
      WantedBy=multi-user.target
      [Service]
      TimeoutStartSec=0
      ExecStart=/usr/bin/docker run \
        --env "KMS_SECRETS_OUT_PATH=/secrets/secrets.env" \
        --env "AWS_DEFAULT_REGION=${aws_region}" \
        --env "KMS_DRONE_SECRET=${kms_drone_secret}" \
        --volume drone-agent-secrets:/secrets \
        lrvick/kms-decrypt
  - name: drone-agent.service
    enable: true
    content: |
      [Unit]
      Description=Drone CI Agent
      Requires=drone-agent-secrets.service
      After=drone-agent-secrets.service
      [Install]
      WantedBy=multi-user.target
      [Service]
      Restart=always
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker kill %p
      ExecStartPre=-/usr/bin/docker rm %p
      ExecStartPre=/usr/bin/docker pull drone/drone:0.5
      ExecStart=/usr/bin/docker run \
        --name %p \
        --volumes-from drone-server \
        --volumes-from drone-agent-secrets \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --entrypoint "/bin/sh -c" \
        --env DRONE_SERVER=ws://drone-server:8000/ws/broker \
        drone/drone "source /config/secrets.env; /usr/local/bin/droned"
      ExecStop=/usr/bin/docker stop %p
